#!/bin/bash -x
#
# This binary can be used as a mock Terraform during tests. It can trigger the
# success or failure of a Terraform apply by ending the module path in either
# "succeed" or "fail".
#
echo "Testing Terraform call:" "$@" >&2

declare -a args=("$@")

# Read arguments
action="${args[0]}"
module_path="$(pwd)"

case "$action" in
    init|get|remote)
        exit 0
        ;;
    apply)
        if [ "$(basename "$module_path")" == "fail" ]; then
            exit 1
        else
            exit 0
        fi
        ;;
    version)
        cat <<EOF
Terraform v0.8.8
EOF
        exit 0
        ;;
esac

exit 1
